.rootWrapper {
    width: 500px;
    margin: auto;
    padding-top: 50px;
    text-align: center;
}

.todoTitle {
    font-size: 24px;
    height: 40px;
    line-height: 40px;
    font-weight: bold;
    color: rgb(45, 183, 245);
}

.btn {
    width: 30px;
    font-size: 13px;
    height: 30px;
    line-height: 30px;
    text-align: center;
    padding: 0 5px;
    cursor: pointer;
    background-color: rgb(45, 183, 245);
    color: #fff;
    border-radius: 3px;
}

.todoContent {
    margin: 20px auto;
    background-color: #eee;
    padding: 20px;
    .todoItem {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 0 20px;
        height: 50px;
        line-height: 50px;
        font-size: 16px;
        background-color: #c8e1ff;
        margin-bottom: 10px;
        &:last-child {
            margin-bottom: 0;
        }
        .todoItemContent {
            flex: 1 1 auto;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }
        .delTodoItem {
            flex: 0 0 30px;
            margin-left: 20px;
        }
    }
}

.todoFooter {
    display: flex;
    justify-content: center;
    & > input {
        width: 150px;
    }
    .btn {
        margin-left: 10px;
    }
}
